apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: kube-data
    namespace: kubeapps
spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Gi
    storageClassName: premium
